### ISSUE TITLE
Web Fonts do not render, use fallback fonts instead.

### ISSUE THREAD

**Issue by atheken** [ariya/phantomjs#10592]
_**[atheken@gmail.com](http://code.google.com/u/atheken/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.5.1 (development)
> 
> <b>What steps will reproduce the problem?</b>
1. Using rasterize.js generate a png of https://developers.google.com/webfonts/
> 2. You should see stylized text for some of the web fonts.
> 
> <b>What is the expected output? What do you see instead?</b>

> --see actual/expected images. Web fonts use their fallbacks instead of the &quot;real&quot; fonts.
> 
> <b>Which operating system are you using?</b>

> Windows 2008 R2
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> no, downloaded the (1.5.0 static package from the project website)
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #592](http://code.google.com/p/phantomjs/issues/detail?id=592).
:star2: &nbsp; **30** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed in master.

**Comment by malhotrar** [comment]
@Vitallium - I've compiled master (using build.cmd for windows) and am still encountering issues loading woff files. Am I missing something?

**Comment by Vitallium** [comment]
@malhotrar make sure you compiled it with zlib support.

**Comment by malhotrar** [comment]
@Vitallium - in preconfig.cmd, I see 'set QT_CONFIG=!QT_CONFIG! -qt-zlib', isn't that what I need or Is there something specific I need to do?

**Comment by Vitallium** [comment]
@malhotrar QtWebkit has its own system to detect if zlib library is available.

**Comment by malhotrar** [comment]
@Vitallium - so what do I do? Anything special i need to install on windows to compile with zlib?

**Comment by Vitallium** [comment]
@malhotrar as far as I remember, you don't. But let me check it.

**Comment by malhotrar** [comment]
@Vitallium - Is there a nightly build, I could try out that would be compiled with zlib support? That way I can make sure it's not an issue with my build?

**Comment by malhotrar** [comment]
I can confirm, I am compiling with zlib (looking at the build log)

Third Party Libraries:
    ZLIB support............qt

qxml.cpp
	cl -c -nologo -Zm200 -Zc:wchar_t -FS -Zi -MTd -MP -W3 /Fd..\..\..\lib\Qt5Bootstrapd.pdb -DUNICODE -DWIN32 -DQT_BOOTSTRAPPED -DQT_LITE_UNICODE -DQT_NO_CAST_TO_ASCII -DQT_NO_CODECS -DQT_NO_DATASTREAM -DQT_NO_LIBRARY -DQT_NO_QOBJECT -DQT_NO_SYSTEMLOCALE -DQT_NO_THREAD -DQT_NO_UNICODETABLES -DQT_NO_USING_NAMESPACE -DQT_NO_DEPRECATED -DQT_NO_TRANSLATION -DQT_QMAKE_LOCATION=\"C:/dev/phantomjs/src/qt/qtbase/bin/qmake\" -DQT_CRYPTOGRAPHICHASH_ONLY_SHA1 -DQT_NO_CAST_FROM_ASCII -DQT_BUILD_BOOTSTRAP_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -D_USE_MATH_DEFINES -DQT_NO_EXCEPTIONS -I"..\..\..\include" -I"..\..\..\include\QtCore" -I"..\..\..\include\QtXml" -I"..\..\..\include\QtCore\5.3.0" -I"..\..\..\include\QtCore\5.3.0\QtCore" -I"C:\dev\phantomjs\src\qt\qtbase\include\QtXml\5.3.0" -I"C:\dev\phantomjs\src\qt\qtbase\include\QtXml\5.3.0\QtXml" -I"tmp" -I"..\..\3rdparty\zlib" -I"..\..\..\mkspecs\win32-msvc2013" -Fo.obj\debug\ @C:/Users/RMALHO~1/AppData/Local/Temp\nmE678.tmp
adler32.c
compress.c
crc32.c
deflate.c
gzclose.c
gzlib.c
gzread.c
gzwrite.c
infback.c
inffast.c
inflate.c
inftrees.c
trees.c
uncompr.c
zutil.c

**Comment by Vitallium** [comment]
@malhotrar found. There is a problem in build.cmd. It doesn't append INCLUDE and LIB dirs for zlib.

**Comment by malhotrar** [comment]
All I should is add the following?:

:: zlib
set ZLIB_DIR=!_3RDPARTY!\zlib
set ZLIB_LIB=!ZLIB_DIR!\lib
set ZLIB_INCLUDE=!ZLIB_DIR!\include

:: sqlite
set SQLITE3SRCDIR=!ROOT_DIR!\src\qt\qtbase\src\3rdparty\sqlite

set LIB=!OPENSSL_LIB!;!ICU_LIB!;!LIBXML_LIB!;!ZLIB_LIB!;%LIB%
set INCLUDE=!OPENSSL_INCLUDE!;!ICU_INCLUDE!;!LIBXML_INCLUDE!;!ZLIB_INCLUDE!;%INCLUDE%
set PATH=!_3RDPARTY!\gnuwin32\bin;%PATH%

**Comment by Vitallium** [comment]
@malhotrar do compile with zlib support, do following:
- clean your Webkit dir (`cd src\qt\qtwebkit` and execute `git clean -dxfq .`)
- download and apply this patch to enable zlib in QtWebkit - https://gist.github.com/Vitallium/a6098ac4b411eb4adbd4
- run `build.cmd` as usual

**Comment by malhotrar** [comment]
@Vitallium - hitting "LINK : fatal error LNK1181: cannot open input file 'z.lib'"

**Comment by malhotrar** [comment]
@Vitallium - renaming zlib.lib to z.lib fixes the issue above.

**Comment by sosso** [comment]
Does anyone have a compiled build for ubuntu 14?

**Comment by bprodoehl** [comment]
@sosso I posted some 2.0 pre-release binaries here: https://github.com/bprodoehl/phantomjs/releases

I didn't expect the static builds for Linux to take this long, so I'll post some 2.0.0 release binaries for Ubuntu there tonight.

**Comment by sosso** [comment]
Awesome.  These have the web font support?  I have a working 2.0 binary but our designer doesn't think the web font support was enabled on the build that I obtained.

**Comment by bprodoehl** [comment]
I posted some new Ubuntu 14.04 and 15.04 binaries here:

https://github.com/bprodoehl/phantomjs/releases/tag/v2.0.0-20150528

Web fonts look just fine using the rasterize example on a couple internal sites, and http://thisweeksplaylist.co/

**Comment by sosso** [comment]
Nice, that's a definite improvement.  

Source:  http://crowdfunding-projects.findthedata.com/w/a1XMTxO8hdX
Phantomed:  https://s3.amazonaws.com/uploads.hipchat.com/21163/408327/dexjshNiINoMQvz/upload.png

**Comment by evgeniymweb100** [comment]
Does anyone have a compiled windows build from master with zlib?
I spent hours, compiling phantomjs on windows (using modified build.cmd with zlib dirs) but all i got - phantomjs.exe without woff support (there is a string "WOFF support requires QtWebKit to be built with zlib support." inside exe). Can't figure out how to make zlib-enabled windows build.

**Comment by derrickstaten** [comment]
Could someone comment on usage? Sorry to bother. I cannot get this working for the life of me. 

Running 2.0.0 on Yosemite, installed view Homebrew. Absolutely beautiful product. Everything is working except Google fonts. 

```
<link href='https://fonts.googleapis.com/css?family=Open+Sans:700,300' rel='stylesheet' type='text/css'>
<style>
.bold {
    font-family: 'Open Sans', Helvetica, serif;
    font-weight: 700;
}
</style>
```

**Comment by evgenosiptsov** [comment]
In some cases need to install Linux version of Arial, Sanserif fonts
`yum install liberation-sans-fonts.noarch`

**Comment by dbashyal** [comment]
@evgenosiptsov thx for that. I was getting boxes instead of text in pdf. Now it's rendering text but quite large ones compare to on my windows and other linux boxes. Atleast, this is better than dark boxes :+1:

**Comment by db-add2** [comment]
Short (bad) workaround:
casper.userAgent('Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5') this UA forces google to load ttf instead of woff files.
