### ISSUE TITLE
CSS not respected: page-break-inside: avoid;

### ISSUE THREAD

**Issue by elistevens** [ariya/phantomjs#10638]
_**[wickedg...@gmail.com](http://code.google.com/u/110915284365508390001/) commented:**_
> Which version of PhantomJS are you using?
> 
> 1.6.0
> 
> 
> <b>What steps will reproduce the problem?</b>
1. Edit pageBreakAvoid.coffee to point to a local pageBreakAvoid.html
> 2. Run the pageBreakAvoid.coffee script with CasperJS v1.0.0-RC1
> 3. Open the resulting phantomjs-pageBreakAvoid.pdf
> 
> <b>What is the expected output? What do you see instead?</b>

> The &quot;bar&quot; div should not be split between the first page and the second; it should start on the second (it should look similar to the chrome PDF).  Instead, it's split in the middle.
> 
> 
> <b>Which operating system are you using?</b>

> PhantomJS is running on Ubuntu 12.04, and the Chrome that produced the comparison PDF is running on OSX 10.7.3
> 
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> I downloaded the 1.6.0 binary release.
> 
> 
> <b>Please provide any additional information below.</b>

> Safari 5.1.3 also exhibits this problem, but Chrome 20.0.1132.47 does not.
> 
> It looks like there's a patch for WebKit that hasn't made it in yet:
> 
> https://bugs.webkit.org/show_bug.cgi?id=5097
> 
> This looks tangentially related, but I haven't found a clear &quot;add this feature&quot; but in Chromium:
> 
> http://code.google.com/p/chromium/issues/detail?id=56246

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #638](http://code.google.com/p/phantomjs/issues/detail?id=638).
:star2: &nbsp; **10** people had starred this issue at the time of migration.

**Comment by stlouisweb** [comment]
I was having issues with page breaks in a table with many rows and the problem for me was that I had overflow set to visible.
Changed 
```css
* { 
  overflow: visible;
}
```
to
```css
* {
  overflow: hidden;
}
```
and the problem seems to go away, no more content cut-off at the margins.
I'm using Phantom v 1.9.7

**Comment by atamanvega** [comment]
Ximi  works great!!

Thank you so much

**Comment by tacone** [comment]
What's the status of this in 2.0 ?

**Comment by zackw** [comment]
Using examples/rasterize.js and the test html file from @gabehollombe, this appears to be fixed in PhantomJS 2.0.  2.0 includes a major update to Webkit, so that's consistent with this having been fixed there in 2010.

(We are painfully aware of how hard it is to update PhantomJS to newer Webkit and we are looking into solutions.)

**Comment by mickaelandrieu** [comment]
@zackw good news ! let's wait for 2.0.1 and this will be fixed in CasperJS ;)

**Comment by ngdaddikar** [comment]
Any solution for v2? It's making things unusable.

**Comment by griggsk** [comment]
The unbreakable css hack didn't work for me. But changing it to this did. 
.unbreakable {
	    display: table;
}

**Comment by shaidams64** [comment]
the display inline block did not work for me, I am using phantomjs 2.0. Also, do you still need to set page.paperSize in phantomjs script even when you are setting page breaks in css? I really appreciate it if somebody could help me. I am trying to generate pdf reports and this is the last bit of the puzzle!

**Comment by gusgard** [comment]
@tacone solution works for me

Good hack "The reasoning behind is that webkit already tries to preserve images from breaking. And images are inline-blocks."

**Comment by mattoz0** [comment]
Thought i would add another solution just incase until this fix makes its way into a binary.
I managed to get page-break-before/after and inside to work in conjunction with CSS3 Regions. The browser support is pretty terrible however phantomjs by chance works.

Use -webkit-flow-from: flow-1-test; and -webkit-flow-into: flow-1-test; (you will need to look into css3 regions documentation for this one).

I used markup similar to this in order to add regions.
`<section class="rendered_to_page container">
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
</section>`
Each of these regions represent pages.

`.rendered_to_page div {
    -webkit-flow-from: flow-1-test;
    height: 363mm;
    page-break-inside:avoid;
  }`
This css was used to style the regions to fit on a page (this will need modification based on your individual needs).

I then used this javascript in my config.js (phantomjs) to remove additional pages.
`page.evaluate(function () {
		// Cull extra pages :)
		var flow = document.webkitGetNamedFlows()['flow-1-test'];
          	var offset = flow.firstEmptyRegionIndex+1;
          	var regions = document.querySelectorAll('.rendered_to_page div:nth-child(n+'+offset+')');
          	for (i = 0; i < regions.length; i++) {
          	    regions[i].style.display = 'none';
         	}	
		});`

I found this solution had less issues than the above suggested solutions for very large documents where more control over page breaks were required.

Hope this helps someone :)

**Comment by tiborsaas** [comment]
I had the same issue. I was fixed by the `display: inline-block` method. But keep in mind, that if the elements you want to break to new pages has a parent that's also `inline-block` then it won't work. Cost me some time to realize :)

**Comment by hodc** [comment]
phantomj 2.1 - fixed by creating the table dnamicly and calculate the height each row with dynamicly add page-break-after on new div table

**Comment by zhongkai** [comment]
phantomjs-2.1.1-linux-x86_64 in centos still not work (both inline-block & page-break-inside: avoid;)

**Comment by ranjansaga** [comment]
I have a table with large amount of data. I tried using the css suggested by @tacone : 

.unbreakable
{
    /* page-break-inside: avoid !important; <-- doesn't work*/
    display:inline-block;
}
.unbreakable:after
 {
    display:block;
    height:0px;
    visibility: hidden;
}

I tried defining the class=unbreakable over table, tr and td. But did not work.

**Comment by mozgras** [comment]
+1 Using phantomjs-2.1.1-linux-x86_64.tar.bz2 .unbreakable class does not help.

**Comment by tomcat90** [comment]
+1 I'm using phantom v2.1.1 and still getting weird splits on a Mac.

**Comment by Dyktus** [comment]
:+1: Still having this issue

**Comment by janlukasschroeder** [comment]
Thanks @drdla I changed your code a bit so that the final layout actually stays the same without being distorted:

body > * { width: 99.999%; zoom: .999; }

After adding the snippet above, I added the snippet below to all elements that should be unbreakable.

.unbreakable { page-break-inside: avoid !important; }

**Comment by skylarmb** [comment]
This issue still exists on 2.1.1. `page-break-inside` seems to have no effect

**Comment by juergengunz** [comment]
any update o page-break-inside on tables?
@skylarmb  did you end up with a workaround?

**Comment by skylarmb** [comment]
@juergengunz I did not. :/ still waiting

**Comment by AndrPetrov** [comment]
any update about that?

**Comment by mhourahine** [comment]
Why is this issue closed?  It hasn't been fixed, has it?

**Comment by skylarmb** [comment]
+1 Why was this closed? This is not fixed.

**Comment by mhourahine** [comment]
FWIW, a workaround the helped me was to wrap the td content with a div:

css:
```
.avoid-break {
  page-break-inside: avoid;
  margin: 0;
  padding: 0;
}
```
html:
```
<table>
  <tr>
   <td>
     <div class="avoid-break">
       <!-- content goes here -->
     </div>
   </td>
 </tr>
</table>
```

**Comment by 54huige** [comment]
How is it now?

**Comment by architech99** [comment]
@54huige Still an issue as far as I know. I've been migrating to Puppeteer implementations for document generation.
