### ISSUE TITLE
Date parsing deviates from Chrome

### ISSUE THREAD

**Issue by emirkin** [ariya/phantomjs#11151]
Best shown by example:

```
phantomjs> new Date("May 8")
"Invalid Date"
phantomjs> new Date("May 8 2013")
"2013-05-08T07:00:00.000Z"
```

In Chrome, both strings are parsed into the same date. Thoughts?

**Comment by jnu** [comment]
@jdelibas that one appears to be https://bugs.webkit.org/show_bug.cgi?id=130123. Able to reproduce in Phantom 2.

**Comment by davidlehn** [comment]
PhantomJS 2.1.1 still has the WebKit bug referred to by @jnu.  It was fixed in WebKit on 2014-03-14.  Parsed dates from 2034-03-01 to 2100-02-28 are wrong.

```
phantomjs> new Date('2034-02-28')       
"2034-02-28T00:00:00.000Z"
phantomjs> new Date('2034-03-01')
"2034-02-28T00:00:00.000Z"
phantomjs> new Date('2100-02-28')
"2100-02-27T00:00:00.000Z"
phantomjs> new Date('2100-03-01')
"2100-03-01T00:00:00.000Z"
```

**Comment by wallw-bits** [comment]
We are still seeing date inconsistencies with Chrome for the following values (the local timezone is -0700):

    phantomjs> new Date('2014-01-30 12:34:56')
    Invalid Date
    phantomjs> new Date('2014-01-30T12:34:56+0000')
    Invalid Date
    phantomjs> new Date('2014-01-30T12:34:56-0700')
    Invalid Date

Chrome parses those as:

    2014-01-30T19:34:56Z
    2014-01-30T12:34:56Z
    2014-01-30T19:34:56Z

**Comment by seyDoggy** [comment]
I'm glad I found this thread. I've been trying to render a page with charts on it, and you can imagine how many Date objects get used. Nothing was working, I thought I was going crazy until I ran:

```sh
phantom> new Date('2017-01-13 01:14')
Invalid Date
```

WAT?

**Comment by wgroeneveld** [comment]
We're using the beta Phantom 2.5 build and dates are still fucked up so the Qt update did nothing to fix any of that. Trying to compare dates (somedate < currdate) to see which one is in the past works 1 out of 5 runs... We're running jasmine on top of Phantom so our tests are becoming flaky due to this issue.

Any progress or updates?

**Comment by AkA84** [comment]
Running BackstopJS (which is using PhantomJS to work) and I encountered this error as well and I can't take diff screenshots of certain pages anymore.

Any updates?

**Comment by wallw-bits** [comment]
@ktiedt try headless Chrome/Firefox instead. I believe the addition of that flag to those browsers has rendered this project obsolete.

https://developers.google.com/web/updates/2017/04/headless-chrome
https://developer.mozilla.org/en-US/Firefox/Headless_mode

**Comment by ktiedt** [comment]
@wallw-bits yeah after posting, I learned that Phantom is no more, thanks for the links, those I had not come across yet.
