### ISSUE TITLE
HTTP PATCH requests do not send body

### ISSUE THREAD

**Issue by sgsabbage** [ariya/phantomjs#11384]
Much in the same vein as issues #11367 and #10873 , sending an AJAX PATCH request does not send the body, and instead just sends a blank body. PATCH requests are documented in [RFC5789](http://tools.ietf.org/html/rfc5789), and are supported by all the browsers I've tested in.

Arguably, it also exists in [RFC2068](http://tools.ietf.org/html/rfc2068#section-19.6.1.1), but I'm aware that that does label it an 'experimental' feature.

**Comment by swebb** [comment]
Summary:

1) Qt 4.8 doesn't support patch with a body (see [here](https://bugreports.qt.io/browse/QTBUG-42456)). Qt5 does support patch with a body.
2) phantomjs 1.9 is built against qt 4.8 (see [here](https://github.com/ariya/phantomjs/blob/1.9/src/qt/README#L1))
3) phantomjs 2 is build against Qt 5, so in theory this should be automatically fixed. However, there is no release date for that.
4) @frobean's patch can be used to make this work (haven't tried it myself).
5) I couldn't find any intention of getting @frobean's patch merged.

**Comment by mockdeep** [comment]
Just ran into this issue myself. Switching it to `put` worked.

**Comment by jakubmal** [comment]
BTW PhantomJS 2.0 is going to be out soon.

**Comment by dholdren** [comment]
this is fixed in 2.0, shouldn't this be closed?

**Comment by sfontana** [comment]
I don't think this was fixed in 2.0, sadface.

**Comment by 3rd-Eden** [comment]
How is this not resolved yet?! There are patch files and countless of people needing this.

**Comment by Sinewyk** [comment]
It is fixed in 2.0, did a quick test case to confirm it. It's just that 2.x cannot take off until binary are available for all platforms so, wait or help =)

**Comment by reidcooper** [comment]
I am having this issue currently. PhantomJS 2.1.X. My BackboneJS PATCH requests are sending empty body requests to my rails api.

**Comment by andremleblanc** [comment]
I had this problem too, I just switched to PUT for now; but, it would be nice to have this.

**Comment by dholdren** [comment]
This bug is back in 2.1 ?

**Comment by reidcooper** [comment]
On my local machine, I am properly able to perform a PATCH request with the body that I want, however I am using Semaphore for my CI. My same tests do not perform the PATCH requests. I am curious on what could not be sending them.

**Comment by dholdren** [comment]
@reidcooper semaphore defaults to PhantomJS 1.9.8 https://semaphoreci.com/docs/phantomjs.html

**Comment by reidcooper** [comment]
@dholdren that seems to have fixed my problem, thanks a lot. However, I did not think about this before because in my Gemfile.lock, I do have version 2.1 of phantomjs?

**Comment by kannans** [comment]
👍  PUT method working thanks @here
