### ISSUE TITLE
PhantomJS 2 remote debugging is broken

### ISSUE THREAD

**Issue by iradul** [ariya/phantomjs#12864]
After running phantomjs with _--remote-debugger-port=8080_ and trying to debug with Google Chrome (Version 39.0.2171.95) "about:blank" link is missing. Also I tried to forcefully go to http://127.0.0.1:8080/webkit/inspector/inspector.html?page=1 but that produces empty page with no debugging capabilities.
Tested on Windows 7 with PhantomJS 2.0 built from source.

**Comment by Pharb** [comment]
The remote debugger works on Ubuntu with the latest PhantomJS master built from source, but the links to the webkit inspector are broken.

What's the HTML source of http://127.0.0.1:8080 ?

**Comment by iradul** [comment]
With http://127.0.0.1:8080 I'm getting exactly the same HTML source that you are getting. 
But by following the link http://localhost:8080/webkit/inspector/inspector.html?page=1 browser is getting empty page with 404 status: ```HTTP/1.0 404 Not OK```

**Comment by Vitallium** [comment]
Confirmed.

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/pull/12899

**Comment by iradul** [comment]
I don't think this is fixing the problem (tested in Windows only). Remote debugger inspector page still not shows *about:blank* link. This time opening http://127.0.0.1:8080/webkit/inspector/inspector.html?page=1 in Chrome will load inspector page, so no more 404 code, but debugging will still not working. You can't set proper breakpoints inside *__run* function (or you can but they are ignored), though you can execute script with *__run()* call from console. I also noticed that GUI is different from what we had in PhantomJS 1.9 (probably because of newer WebKit version).

**Comment by iradul** [comment]
This is workaround that works for me, in *utils.cpp* replace *loadJSForDebug* with this:
```cpp


bool loadJSForDebug(const QString& jsFilePath, const QString &jsFileLanguage, const Encoding& jsFileEnc, const QString& libraryPath, QWebFrame* targetFrame, const bool autorun)
{
    QString scriptPath = findScript(jsFilePath, libraryPath);
    QString scriptBody = jsFromScriptFile(scriptPath, jsFileLanguage, jsFileEnc);

    if (!autorun) {
        scriptBody = "function __run() {\n" + scriptBody + "\n}";
    }

    targetFrame->evaluateJavaScript(scriptBody, QString("debugger"));
    
    return true;
}
```

Then while remote debugging there will be *(no domain)* item in *Sources* panel and inside of it will be *debugger* from where you can properly set breakpoints. Also for me this *debugger* page is accessible and can be seen only using arrow keys and not by mouse.
Side effect is that there is no more need for *remote_debugger_harness.html* resource.

**Comment by Vitallium** [comment]
@iradul can you please show me a small example? In my case I can debug JS code (on Windows).

**Comment by iradul** [comment]
Using PhantomJS 2.0 binary built from source (remote debugging with binary from [website] (http://phantomjs.org/download.html) doesn't work at all) and running remote debugger on this *test.js* script:
```javascript
require('webpage').create().open('http://google.com', function() {
	console.log('ok!');
	phantom.exit();
});
```
```
phantomjs.exe --remote-debugger-port=8080 test.js
```
with Google Chrome I'm getting this:
![debugger_01](https://cloud.githubusercontent.com/assets/2411422/5994542/b4385ad2-aa46-11e4-93ef-0862bbe163bc.png)

Now if I open http://localhost:8080/webkit/inspector/inspector.html?page=1 manually see below:
![debugger_02](https://cloud.githubusercontent.com/assets/2411422/5994607/b4109f72-aa48-11e4-9dda-a8c9dfe00be6.png)

I'm getting same behavior on 3 different Windows 7 machines.

**Comment by ariya** [comment]
@Vitallium With your check-in in 2.0 branch (to include Web Inspector resource, from around Jan 24), I assume this issue is fully addressed? If yes, then probably it's a good idea for us to roll out 2.0.1 with this fix.

**Comment by Vitallium** [comment]
@ariya I can, but there are still a small bunch of issues, that I'd like to fix. I'll list them here #12970

**Comment by ariya** [comment]
@Vitallium Those can still go to 2.1, don't they?

**Comment by Vitallium** [comment]
@ariya I think so.

**Comment by aschmalzhaf** [comment]
Can anyone confirm that the changes done in February fix the reported issue?
PhantomJS is completely new to me, but when I did a build two days ago on Windows (branch 2.0 - I can see the changes) I still see the  behavior described by iradul on Feb. 2nd in this thread. 

Has anybody else tried to buld PhantomJS from sources - and saw a working debugger?

**Comment by iradul** [comment]
Issue is not completely fixed, as I explained [here](https://github.com/ariya/phantomjs/issues/12864#issuecomment-72393848).

**Comment by aschmalzhaf** [comment]
@iradul, I asked because the fix was done on Feb 5th - your comment was written on Feb 2nd (see fix here: https://github.com/ariya/phantomjs/commit/8e8546b39c7cf807b4033fe4404f8ba2db90ec52). 
So I thought when I read the thread that it is actualy fixed (or: should be...).

Thanks for your statement here, again, that it isn't completely fixed.

**Comment by LeMoussel** [comment]
One idea when PhantomJS Release 2.0.1 will be available to download?

**Comment by bedney** [comment]
Still seeing the issues that @iradul was seeing on Feb 5th. Any ETA on 2.0.1?

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/commit/8b79f62faf7335b8498770e01122b15d1405684b

**Comment by logankd** [comment]
How can I get this patch? Is there a release planned for 2.0.1? I'm trying to debug with 2.0 and found this issue. I ran build.cmd, but don't have nmake or qmake or Perl setup on my Windows machine.
Thank you.

**Comment by skitterm** [comment]
I'm getting the page with just the dot, then when I go to the directory listed in the source html, I see a blank page.
(I'm using Phantom 2.0 downloaded from the phantom site, with Windows 8 and Chrome 44)

**Comment by jcope2013** [comment]
any tips on building from master on mac yosemite so i can get this patch

**Comment by ronanamsterdam** [comment]
really hoping to get new releases (both for osx and windows) soon. pleeeease :pray: :pray: :pray:

**Comment by iradul** [comment]
@Vitallium you should consider reopening this issue, after testing on the current master branch it looks like phantom's script body is missing from sources tab:
`phantomjs --remote-debugger-port=8080 test.js`

![rdpbug](https://cloud.githubusercontent.com/assets/2411422/12203577/acbe5892-b5fd-11e5-9b3f-1e3c04835263.png)

I have a fix for this.

**Comment by Vitallium** [comment]
@iradul uh, I thought we got it fixed.

**Comment by garethbrown** [comment]
I can confirm I'm still experiencing the same issue on windows with the latest release.

**Comment by schatekar** [comment]
I am trying this with version `2.0.0` on Windows 8.1 and seeing empty page

**Comment by Vitallium** [comment]
Landed in master! Thanks!

https://github.com/ariya/phantomjs/commit/0e32928ae167b1f756a8324bd1602200f6e9227e

**Comment by schatekar** [comment]
I am new here so sorry for silly question - How do I know when this fix will be released? Is there a way I can use this fix right away?

**Comment by scottgrohusky** [comment]
The about:blank link is missing for me as well when remote debugging.  I'm using phantomjs 2.1.1 on windows 10.  I ran at the command line:

phantomjs --remote-debugger-port=9000 --remote-debugger-autorun=true practice2/chapter01/recipe08.js

However a link to the js file I want to debug is displayed.  But Breakpoints are not being hit in the web inspector and nothing is written to the console after entering __run().

![about_blank_missing](https://cloud.githubusercontent.com/assets/2687267/22752019/c784de90-edeb-11e6-80d7-a20306e4c4df.png)

![no_debug_breakpoints_or_console](https://cloud.githubusercontent.com/assets/2687267/22752163/5dbe7f56-edec-11e6-8c25-a74a362c44b7.png)

**Comment by iradul** [comment]
You should not use `--remote-debugger-autorun=true`
With that option on phantom will immediately execute `__run()` internally so while you're loading `localhost:9000` into Chrome your phantom script probably already ended.

**Comment by scottgrohusky** [comment]
I think this is a [dupe issue](https://github.com/ariya/phantomjs/issues/14408) which is open.

I ran:

`phantomjs --remote-debugger-port=9000 practice2/chapter01/recipe08.js`

and

`phantomjs --remote-debugger-port=9000 --proxy-type=none practice2/chapter01/recipe08.js`

Breakpoints are still not being hit and __run() does not output anything.  

![about_blank_missing2](https://cloud.githubusercontent.com/assets/2687267/22761355/3c2a31f0-ee0f-11e6-8759-20df5bc6d0d5.png)

![no_breakpoints_or_console](https://cloud.githubusercontent.com/assets/2687267/22761371/463ec066-ee0f-11e6-837f-cc8ac12df4d0.png)

**Comment by sontek** [comment]
I'm seeing the same thing, the console doesn't actually run the `__run()` command, it inserts a newline in Chrome.  The console doesn't work at all in Firefox.  It works perfectly in safari though.

**Comment by jesobreira** [comment]
Same issue. `__run()` + <kbd>enter</kbd> just adds a line feed on the console window and I am unable to get it running. Chrome on Ubuntu 16.10.

**Comment by wgiroir** [comment]
I have also verified that this failed on using Chrome and Firefox but works with Safari

**Comment by jesobreira** [comment]
@wgiroir what OS are you using? I couldn't get it working on Safari on Win7.

**Comment by sontek** [comment]
I'm safari + OSX

**Comment by wgiroir** [comment]
I was running Safari on OSX and phantomjs on CentOS 7

**Comment by jesobreira** [comment]
I could run the debug using a very old Chrome version (Chrome 17) that I download [here](http://www.mediafire.com/file/dw17nkejsba3o7n/GoogleChromePortable.rar) (run sandboxie-d as I can't confirm the procedence of it, although it worked with me - do not use it for browsing, use it for debugging your PhantomJS scripts only).

**Comment by Galleleo** [comment]
[Arora](https://github.com/Arora/arora) works for me! It's a browser based on Qt and WebKit and displays pages like Safari does. I tried Chrome on Ubuntu 16.10 as well as Safari 5.0.5 in Wine but Arora is (so far) the only browser that executes `__run()`

**Comment by lewsid** [comment]
Any word on this? I'm running PhantomJS 2.1.1 on OSX and the debugger simply doesn't work in any browser I try. I get the same thing others have reported: Entering the `__run()` command returns nothing, and no breakpoints are ever hit.

**Comment by lewsid** [comment]
For those like me still having trouble, I've found that using an old version of Chromium works well, if your default browser is Chrome. Here's a link to a 2014 build of Chromium that I've had luck getting to work with PhantomJS's remote debugger: https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2F280075%2Fchrome-mac.zip?generation=1409176787550000&alt=media

**Comment by jumoreno** [comment]
@lewisd, I can confirm I can get chrome debugger to work in the old Chromium version. Will try and understand why this is and post on here if I find anything. I have been looking for other remote debugging breakpoint options for casperjs and will post here if I find anything that works as well. Seems like we need to add support for latest Chrome though.

**Comment by iradul** [comment]
For those who use [Code editor](https://code.visualstudio.com/), you can use PhantomJS debugger extension.

**Comment by twalpole** [comment]
This is because the protocol used by Chrome changed after the Webkit- Blink engine split.

**Comment by lewsid** [comment]
This issue should be re-opened, no?

**Comment by jumoreno** [comment]
@iradul thanks for the heads up on the Code editor debugger extension -> do you happen to know runtime configuration required for a Mac? Took a quick look [here](https://code.visualstudio.com/docs/editor/debugging) so far and played a bit with it but no success so far.

**Comment by iradul** [comment]
Hmm never tested on Mac but should be straight forward if you follow steps from documentation, check those out:
https://marketplace.visualstudio.com/items?itemName=iradul.debugger-for-phantomjs
https://github.com/iradul/vscode-phantomjs-debug (raise an issue if needed)

**Comment by twalpole** [comment]
@jumoreno Also on a Mac it should work using Safari since IIRC it still uses the same protocol (WebKit based)

**Comment by thorn0** [comment]
This must help: https://github.com/node-inspector/node-inspector/issues/951#issuecomment-262441472

**Comment by mingjunz** [comment]
anyone have workaround for this problem?

**Comment by zorkus** [comment]
@mingjunz, two workrounds:
- Use Chromium 50.x
- Try Tizen Console Fix extension for Chrome.

**Comment by brittotprince** [comment]
I had the same issue and was having a hard time finding chrome 50.x
Attaching the link below for future use
Chrome version: [50.0.2657.12:](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/376886/)

Disclaimer: The below project helped me get this easily. Utilize it in case you need any other version of chrome.
https://vikyd.github.io/download-chromium-history-version/#/
