### ISSUE TITLE
send_keys hang with webdriver - phantomjs 2.0

### ISSUE THREAD

**Issue by oxinferno** [ariya/phantomjs#12985]
I'm new here, so forgive me if I'm not giving all the information that I should be.  My code is the following:

webdriver.find_element_by_xpath(xpath).send_keys(*value)

This code is used for populating both type="file" and type="text" elements.  Using Firefox, this code has no issues.  Using phantomjs, type="text" has no issues.  However, I encounter a hang with type="file".  

System:
Mac 10.9.5
Python 2.7.5
Selenium 2.44.0
PhantomJS 2.0.0

**Comment by JamesMGreene** [comment]
Please submit this to [detro/GhostDriver](https://github.com/detro/GhostDriver/). Thanks!

**Comment by oxinferno** [comment]
Done, thank you!

**Comment by sureshvv** [comment]
I am still facing this issue with phantomjs 2.0. Has this been fixed? How do I use ghostdriver? Is it internally part of phantomjs?
