### ISSUE TITLE
--local-storage-path is still ignored

### ISSUE THREAD

**Issue by jamb0ss** [ariya/phantomjs#13689]
No matter what I pass there, it saves all data into ~/.local/share/Ofi\ Labs/PhantomJS/

OS: Ubuntu 14.04 (x86_64)
PhantomJS: 2.0.0

**Comment by Vitallium** [comment]
This issue was fixed and landed to the master branch - https://github.com/ariya/phantomjs/commit/5c66f389c8c6367209d837485c6f218b9f118f22

**Comment by jamb0ss** [comment]
I use 2.0.0 built from sources (this repo), and still see this issue

**Comment by jamb0ss** [comment]
What's the point to close this issue in a minute? Do you think I'm kidding or what? Nonsense

**Comment by Vitallium** [comment]
Could you please provide a working sample to reproduce your issue?

**Comment by jamb0ss** [comment]
Simple script, like:
    var page = require('webpage').create();
    page.open('http://ya.ru', function (status) {console.log('ok');})

Start it with custom --local-storage-path:
    phantomjs --local-storage-path=ANY_DIR_HERE script.js

http_ya.ru_0.localstorage will be saved into ~/.local/share/Ofi\ Labs/PhantomJS/

Is it an expected behavior?

**Comment by Vitallium** [comment]
Just did quick test.
Command line:
`./phantomjs --local-storage-path=. ../examples/rasterize.js http://yandex.ru out.png`
And localstorage is located in the current dir:
`-rw-r--r--  1 vitaly  staff    12K Oct 28 10:21 http_www.yandex.ru_0.localstorage`

**Comment by jamb0ss** [comment]
The same test:
```
./phantomjs --local-storage-path=. ../examples/rasterize.js http://yandex.ru out.png
```

http_www.yandex.ru_0.localstorage in ~/.local/share/Ofi\ Labs/PhantomJS/

What PhantomJS version do you use? What OS?

**Comment by Vitallium** [comment]
Latest build from sources. OS X El Capitan.

**Comment by jamb0ss** [comment]
Could you upload somewhere your PhantomJS build please?

**Comment by Vitallium** [comment]
https://github.com/Vitallium/phantomjs/releases/tag/2.0.1

**Comment by jamb0ss** [comment]
I've downloaded phantomjs-2.0.1-linux-x86_64.zip archive and started binary from there.
```
phantomjs -v
```
Segmentation fault (core dumped)

**Comment by Vitallium** [comment]
OS? And Paste output of the following command: `ldd phantomjs`

**Comment by jamb0ss** [comment]
it returns "not a dynamic executable"

**Comment by Vitallium** [comment]
I assume you're running X86, not X86-64 operating system, right?
So, you have to compile PhantomJS from sources by yourself.

**Comment by jamb0ss** [comment]
ok, I was able to start your linux build on another linux machine (forget about "Segmentation fault", it's not about this issue), but it still ignores --local-storage-path

**Comment by jamb0ss** [comment]
nope, I'm running x86-64.
```
uname -a
```
Linux ... x86_64 GNU/Linux

**Comment by Vitallium** [comment]
Install fontconfig library to run it.

But, anyway I checked it on my Linux box (Ubuntu Trusty). Still works:
```
drwxrwxr-x 4 vagrant vagrant   4096 Oct 28 08:15 ./
drwxrwxr-x 4 vagrant vagrant   4096 Oct 28 08:12 ../
drwxrwxr-x 2 vagrant vagrant   4096 Oct 23 00:30 bin/
-rw-rw-r-- 1 vagrant vagrant  17266 Oct 22 22:23 ChangeLog
drwxrwxr-x 2 vagrant vagrant   4096 Oct 23 00:30 examples/
-rw-r--r-- 1 vagrant vagrant   3072 Oct 28 08:15 http_www.yandex.ru_0.localstorage
-rw-rw-r-- 1 vagrant vagrant   1429 May  4 11:44 LICENSE.BSD
-rw-rw-r-- 1 vagrant vagrant 144424 Oct 28 08:15 out.png
-rw-rw-r-- 1 vagrant vagrant   3764 Oct  6 23:05 README.md
-rw-rw-r-- 1 vagrant vagrant   1659 Oct  6 23:05 third-party.txt
```

**Comment by jamb0ss** [comment]
I have no idea why, but your build (with fontconfig installed) now respects "local-storage-path" option. Thanks a lot! One more question related to fontconfig (btw, can you add this dependency here http://phantomjs.org/build.html ?) - I see "Fontconfig error: Cannot load default config file" error on each run, do you know how to fix it?

**Comment by Vitallium** [comment]
You see this error, because the Linux build is a bit wrong, It has an additional dependency to `fontconfig`, when it shouldn't. I'll update it soon.

**Comment by jamb0ss** [comment]
I just see how script freezes every time (loading any page) trying to find it and then after a few seconds it show this error and continue loading. Can I turn it off somehow or may be explicitly set this option?

**Comment by Vitallium** [comment]
I'm afraid you can't do that.

**Comment by jamb0ss** [comment]
Ok, I've checked the strace's output, found what was wrong and created a link 
```
ln -sf /etc/fonts /usr/etc/fonts) 
```
Now it doesn't freeze anymore, but I see "Unable to update the static FcBlanks" errors though..
But it works. Thanks for your help and I hope the "fontconfig" dependency will be removed soon.
