### ISSUE TITLE
Crash under OSX when header is set from script 

### ISSUE THREAD

**Issue by dmilith** [ariya/phantomjs#13731]
In this case php script:

<?php
    header('Content-type: image/png');
    ...

and each request from Phantomjs causes a crash like this:

```
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/A90DE3CD-23E4-4425-BEA0-688002A547B8.dmp
```

My system - OSX 10.11.1

**Comment by zackw** [comment]
By sending `Content-type: image/png` you promise that the content is, in fact, a well-formed PNG. Are you *certain* that you are producing a well-formed PNG from this PHP script?  Are you certain that there are no leading or trailing garbage bytes?  Please investigate.

Regardless PhantomJS should not *crash*, but if you can fix your script that will solve your problem much faster than any alternative procedure.  If you tell me the PNG is perfectly well-formed, I'm going to have to tell you first that you need to try PhantomJS 2.0 and second that you need to talk to the Webkit developers, and it's probably gonna be months before you get a fix.

**Comment by dmilith** [comment]
Of course it's a bad script, and yes I already fixed my script. But PhantomJS shouldn't crash this way or another :)

**Comment by zackw** [comment]
OK, so to get it *fixed*, I hope you still have a copy of the bad version of the script, because you need to report this to the Webkit developers (instructions here: <https://www.webkit.org/quality/reporting.html>) and they will want to see the bad PNG file.  (Regrettably, we don't have the manpower to fix Webkit bugs ourselves.)
