### ISSUE TITLE
AJAX load + element replace (sometimes) fails

### ISSUE THREAD

**Issue by drauch** [ariya/phantomjs#13881]
After AJAX requests (where the result is supposed to replace the contents of a div) we sometimes (race condition in the PhantomJS code base?) run into the situation, that PhantomJS (yeah, never happens with ChromeDriver or InternetExplorerDriver) thinks the AJAX result is the complete new page.

We can observe this behavior by taking a browser screenshot with PhantomJS and we can see only the AJAX result, nothing else. This is true even after waiting for 5s and taking another screenshot. Subsequent test stepts fail with NoElementFoundExceptions (as we search for elements outside of the AJAX result...).

This is reproducible in around 50% of the runs, the other 50% do not have the problem and the browser screenshot shows the whole page.

Any ideas?

We're using PhantomJS 2.0.0 on .NET 4.6.1, Win 8.1 via Selenium WebDriver.

**Comment by Vitallium** [comment]
Thank you for submitting this ticket!

This issue tracker primarily serves as the tool to report and track bugs, defects, and development tasks.
For general question, code review request, build problem, or other related discussion, please post it to either:

- the official [PhantomJS users mailing-list](http://groups.google.com/group/phantomjs)
- [Stack Overflow](http://stackoverflow.com/questions/tagged/phantomjs) (with phantomjs tag)
- **NEW!** the public forum for users to discuss questions, request code reviews, ask for an advice, and compare notes in general -http://discuss.phantomjs.org

If you have not read it yet, please check also a few tips on [Effective Q&A](https://github.com/ariya/phantomjs/wiki/Support).

**Comment by drauch** [comment]
> as the tool to report and track bugs
This is certainly a bug in PhantomJS, it looks like a race condition within PhantomJS.

**Comment by Vitallium** [comment]
Without a minimal test case or an example we can't help you.

**Comment by drauch** [comment]
I'm aware that race conditions are hard to find, and that you won't be able to do very much about my filed bug if you don't fancy intense debug sessions and/or parallel flow analysis.

That doesn't change the fact that I reported a legit bug which should not be closed as long as it is not fixed. Closing the bug gives the idea that the problem does not exist. It hinders other people in similar situations to find the issue, etc.

If I ever find a minimal test case I most probably already found the concrete race condition in the PhantomJS code, I would probably provide a pull request instead.

Please keep bug reports open if they are valid bug reports, it is not only disrespectful but also a bad decision to prematurely close issues in open source projects. Thank you.

**Comment by Vitallium** [comment]
I surely understand your position. We have enormous amount of issue here due to incredibly small amount of developers in the team.
We decided to keep the bug tracker as tidy as it possible.

Your issue is about random race conditions, without a simple test case. A test case that we could use to reproduce described race condition or at least to try.
It's hard to fix issues that are: 
- occur randomly
- happens only in particular environment
And, unfortunately, without a reproducible sample nobody will work on it.

Thanks!

You can find more information here: https://github.com/ariya/phantomjs/issues/13865

**Comment by Vitallium** [comment]
@drauch you'll be laughing at me. But I think I found the problem of your issue.

**Comment by drauch** [comment]
@Vitallium: Not laughing, would love to see this fixed. Had lost all hope before :+1:

**Comment by Vitallium** [comment]
Could you please check version from master? It should be fixed now.

**Comment by drauch** [comment]
Is there a pre-built .NET assembly or do I have to compile phantomjs myself in order to test it?

**Comment by Vitallium** [comment]
We have released a new version yesterday. This version included the fix - https://bitbucket.org/ariya/phantomjs/downloads

**Comment by drauch** [comment]
:+1: going to give it a try asap!

**Comment by drauch** [comment]
Unfortunately, the problem isn't fixed. 2.1.1 still gives us screenshots of the AJAX-response only.

**Comment by drauch** [comment]
(on another note: when testing for a 404 page, we also get a screenshot of the previously visited page instead of a 404 page)
