### ISSUE TITLE
error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kazantip151** [ariya/phantomjs#15280]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1
2. What steps will reproduce the problem?
  1. I tried to use phantom on shared hosting and i get this error. It is a problem of hosting? Can be run phantom on shared hosting?

3. Which operating system are you using?
CentOS - linux
4. Did you use binary PhantomJS or did you compile it from source?
binary for linux
5. Please provide any additional information below.

**Comment by pixiuPL** [comment]
@kazantip151 its fixed in the latest version (2.1.3)

**Comment by vanderzago** [comment]
I still having this same issue with binary for linux  - latest version (2.1.3) - on CentOS Linux release 7.3.1611 (Core). I have installed all libs specified in http://phantomjs.org/build.html.. Do I need to open other issue with the same title?

**Comment by vanderzago** [comment]
$ ./phantomjs
./phantomjs: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by pixiuPL** [comment]
@vanderzago No; one issue is enough. 
As of `libssl`error; 2 steps::

1. `sudo apt-get update
sudo apt-get install libssl1.0.0 libssl-dev`
2. `cd /lib/x86_64-linux-gnu
sudo ln -s libssl.so.1.0.0 libssl.so.10 &&
sudo ln -s libcrypto.so.1.0.0 libcrypto.so.10`

**Comment by vanderzago** [comment]
I am using CentoOS 7 and libssl is not avaliable for this version:

# yum search libssl
Warning: No matches found for: libssl
No matches found

Libssl was replacedy by openssl, since CentOS 6.

 I also applied yum update, but the issue persists.

**Comment by pixiuPL** [comment]
@vanderzago what repos do you have enabled?

**Comment by vanderzago** [comment]
# ls /etc/yum.repos.d/
CentOS-Base.repo
CentOS-Debuginfo.repo
CentOS-Media.repo
CentOS-Vault.repo
puppet.repo
CentOS-CR.repo
CentOS-fasttrack.repo
CentOS-Sources.repo
jenkins.repo

**Comment by pixiuPL** [comment]
@vanderzago thanks, but its not what I asked. Look inside each repo definition and find string that starts with enabled=
Please posty them here.

**Comment by vanderzago** [comment]
@pixiuPL thanks for your support. Here is the result of the command: # grep ^enabled= *
CentOS-Base.repo:enabled=0
CentOS-CR.repo:enabled=0
CentOS-Debuginfo.repo:enabled=0
CentOS-fasttrack.repo:enabled=0
CentOS-Media.repo:enabled=0
CentOS-Sources.repo:enabled=0
CentOS-Sources.repo:enabled=0
CentOS-Sources.repo:enabled=0
CentOS-Sources.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
CentOS-Vault.repo:enabled=0
jenkins.repo:enabled=1 
   name=jenkins
puppet.repo:enabled=1 
   name=Puppet Repository el 7 - $basearch
puppet.repo:enabled=0

This server was created via vagrant box for CentOS 7 in a VirtualBox vm in my desktop. 
I am using puppet to deploy a jenkins server and I created a Jenkins job that use phantomjs.

**Comment by n0en** [comment]
I am having the same problem. The pre-made binary for 2.1.1 works fine on my Centos systems but the 2.1.3 gets this error. This seems to be a regression break.

**Comment by pixiuPL** [comment]
I investigated the problem and **its not PJS related** issue. Many other packages have the very same issue. I think its something wrong with g/cc. Probably worth creating an issue on their tracker/whatever they have....

**Comment by n0en** [comment]
I suspect that 2.1.1 was statically linked and that 2.1.3 is dynamically linked. There are cross-distribution issues with dynamically linked binaries. The reason that I think this is that the 2.1.1 binary is about 100K larger than the 2.1.3 binary. I would much prefer that the pre-packaged binary be statically linked so it is distribution independent. While I understand this creates larger binaries, it's much better to be more platform independent.

**Comment by kazantip151** [comment]
so, what i need to do that i`ll get it work on shared hosting?

**Comment by n0en** [comment]
Try the older 2.1.1 pre-built binary and see if that works for you. For me that works on both Ubuntu and Centos.

**Comment by pixiuPL** [comment]
@kazantip151 exactly as @n0en siad. Try prebuilt 2.1.1

**Comment by kazantip151** [comment]
Ok i`ll try thx

**Comment by kazantip151** [comment]
i dont see 2.1.1 biknary.. where is it?

**Comment by wilyarti** [comment]
Same issue here is Fedora. Version 2.1.3 will not run due to missing libraries (they are installled).

**Comment by pixiuPL** [comment]
@wilyarti its not related to PJS. Just google error message. Many programs have it.
Cause of this error message is somewhere else.

**Comment by wilyarti** [comment]
@pixiuPL hey mate. Could someone build a static binary then? I managed to find an old 2.1.1 static binary that worked fine.

**Comment by pixiuPL** [comment]
@wilyarti of course I can build static binary. But Im affraid the problem will not be gone. 2.1.1 works fine, because this error started to appear after **2.1.1** has been released.

**Comment by n0en** [comment]
I would be happy to test a static binary if you can produce one.

**Comment by pixiuPL** [comment]
@n0en sure thing :) will take care of this tomorrow :)

**Comment by kevinmichaelchen** [comment]
Anyone know where I can download a ready-to-use binary of PhantomJS 2.1.1 for 64-bit Linux? The download page (http://phantomjs.org/download.html) only shows one for 2.1.3

**Comment by pixiuPL** [comment]
@n0en have been busy all day fighting with moody compiler who thinks its smarter than me :) Tomorrow fight will continue :)

**Comment by NadezhdaBaranova** [comment]
Hello!

I faced the same problem with phantomjs 2.1.3 (binary) resolved it. 

Solution (for docker container running on Debian):

wget http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2l-1~bpo8+1_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7_amd64.deb

dpkg -i libssl1.0.0_1.0.2l-1_bpo8+1_amd64.deb                                  
dpkg -i openssl_1.0.2l-1_bpo8+1_amd64.deb                                      
dpkg -i libicu55_55.1-7_amd64.deb                                             

Hope it help!

**Comment by n0en** [comment]
Your solution will not work for Centos, however.

**Comment by pixiuPL** [comment]
> Your solution will not work for Centos, however.

Why do you think so?

**Comment by moxx** [comment]
Is it possible to upload an 2.1.1 bin again?

**Comment by pixiuPL** [comment]
@moxx You mean upload where? to repo?

**Comment by moxx** [comment]
@pixiuPL i have found a  binary at https://bitbucket.org/ariya/phantomjs/downloads/ thanks

**Comment by n0en** [comment]
I am referring to NadezhdaBaranova's fix. It will only work for debian derivatives since dpkg is specific to debian. Centos uses the yum package manager and a slightly different versioning scheme.

**Comment by lokori** [comment]
I got it working under CentOS 7 using the older 2.1.1 binary. However, I needed to install some additional stuff to satisfy all the dependencies. So nice.


`./phantomjs: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
yum -y install glibc.i686
 ./phantomjs 
./phantomjs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
yum install zlib.i686
./phantomjs 
./phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
yum install fontconfig freetype freetype-devel fontconfig-devel libstdc++
yum install libfontconfig.so.1
yum install libstdc++.so.6
`

Finally!

**Comment by dockercore** [comment]
> 我使用较旧的 2.1.1 二进制文件让它在 CentOS 7 下工作。但是，我需要安装一些额外的东西来满足所有依赖项。太赞了。
> 
> ```
> 
> yum -y install glibc.i686
>  ./phantomjs 
> ./phantomjs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
> yum install zlib.i686
> ./phantomjs 
> ./phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
> yum install fontconfig freetype freetype-devel fontconfig-devel libstdc++
> yum install libfontconfig.so.1
> yum install libstdc++.so.6
> ```
> 
> 最后！

CentOS Linux release 7.9.2009 (Core)       unable to solve
